version: '3.8'
services:
  server:
    container_name: node
    build: .
    ports:
      - '5000:5000'
    networks:
      - backend
    depends_on:
      - db
    command: bash -c "/usr/wait-for-it.sh --timeout=5 mongodb:27017 && yarn start"
  db:
    container_name: mongodb
    image: mongo
    working_dir: /data
    volumes:
      - mongodata:/data/db
    networks:
      - backend
networks:
  backend:

volumes:
  mongodata:
